name: ping-pi

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Show runner info
        run: |
          echo "=== WHOAMI ==="
          whoami
          echo "=== HOSTNAME ==="
          hostname
          echo "=== UNAME ==="
          uname -a
          echo "=== HOME ==="
          echo $HOME
          echo "=== DOCKER ==="
          docker version || true
          echo "=== DEPLOY DIR ==="
          ls -la /home/actions/deploy/aquapi || true
