name: ping-pi

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Show pi-agent state
        run: |
          whoami
          hostname
          docker ps -a
          echo "-----"
          ls -la /home/actions/deploy/aquaponics/env || true
          echo "-----"
          cat /home/actions/deploy/aquaponics/env/pi-agent.env || true
          echo "-----"
          docker logs --tail 200 pi-agent || true
